const levels = [
    { id: 'beginner', name: 'المستوى المبتدئ', icon: '🌱' },
    { id: 'intermediate', name: 'المستوى المتوسط', icon: '🚀' },
    { id: 'advanced', name: 'المستوى المتقدم', icon: '🏆' }
];

const lessonsList = {
    'advanced': [
        { id: '201', title: '1. Cooperative Sovereignty', description: 'Globalized Era Sovereignty' },
        { id: '202', title: '2. Future of Globalization', description: 'Decoupling Doctrine' },
        { id: '203', title: '3. Modern Conflict', description: 'Information Age Warfare' },
        { id: '204', title: '4. Global Governance', description: 'The Paradox of Sovereignty' },
        { id: '205', title: '5. The Digital Shift', description: 'New Social Contract' },
        { id: '206', title: '6. Hybrid Warfare', description: 'Shifting Dynamics of Deterrence' },
        { id: '207', title: '7. Weaponization of Space', description: 'Orbital Stability' },
        { id: '208', title: '8. Supply Chain Resilience', description: 'Geoeconomics Imperatives' },
        { id: '209', title: '9. Soft Power', description: 'Information Warfare Strategies' },
        { id: '210', title: '10. Autonomous Weapon Systems', description: 'Meaningful Human Control' },
        { id: '211', title: '11. The Arctic Frontier', description: 'Geopolitical Competition' },
        { id: '212', title: '12. Resource Scarcity', description: 'The Water-Energy-Food Nexus' },
        { id: '213', title: '13. Digital Authoritarianism', description: 'Surveillance Capitalism' },
        { id: '214', title: '14. Non-State Actors', description: 'Erosion of the Monopoly on Violence' },
        { id: '215', title: '15. Algorithmic Bias', description: 'Ethics in AI Governance' },
        { id: '216', title: '16. Bio-Security', description: 'Synthetic Biology Risks' },
        { id: '217', title: '17. Cognitive Warfare', description: 'Battle for the Mind' },
        { id: '218', title: '18. Quantum Supremacy', description: 'Cryptography and Security' },
        { id: '219', title: '19. Megacities', description: 'Urban Resilience Challenges' },
        { id: '220', title: '20. Deepfakes', description: 'Post-Truth Geopolitics' },
        { id: '221', title: '21. Circular Economy', description: 'Sustainability Transitions' },
        { id: '222', title: '22. Outer Space Treaty', description: 'Legal Gaps in New Space' },
        { id: '223', title: '23. Migrant Crisis', description: 'Demographic Shifts' },
        { id: '224', title: '24. CBDCs', description: 'Central Bank Digital Currencies' },
        { id: '225', title: '25. Climate Reparations', description: 'Global South Justice' },
        { id: '226', title: '26. The Great Reset', description: 'Economic Transformation' },
        { id: '227', title: '27. Geoengineering', description: 'Climate Intervention Risks' },
        { id: '228', title: '28. Post-Pandemic Order', description: 'Global Systemic Shifts' }
    ]
};

const lessonsData = {
    '201': {
        title: "Cooperative Sovereignty in a Globalized Era",
        content: `Recent decades have witnessed a fundamental transformation in the concept of national sovereignty, driven by the growing power of international institutions and multilateral agreements. Sovereignty, in its classical sense, has long been associated with the absolute right of a state to control its territory, resources, and population without external interference. However, the emergence of transnational challenges such as climate change, cyber-organized crime, and global pandemics has starkly revealed the limits of this concept. States are no longer capable of confronting these challenges individually, which has compelled them to negotiate and cede portions of their authority to global governance bodies.\n\nThis shift propels a model known as "cooperative sovereignty" or "sovereignty as responsibility." Proponents argue that in an interconnected world, the ultimate exercise of sovereignty is the ability to participate effectively in international systems, shape global norms, and protect one's citizens from threats that originate beyond borders. This requires a pragmatic surrender of absolute autonomy in exchange for influence and collective security. For example, a country adhering to World Trade Organization rules accepts constraints on its domestic trade policies but gains access to a dispute resolution mechanism and a vast global market.\n\nCritics, however, view this evolution with suspicion, interpreting it as a dilution of statehood and a potential infringement on national self-determination. They warn that powerful states or unaccountable bureaucracies in international organizations can dominate the rule-setting process, effectively imposing their will on smaller nations under the guise of global cooperation. The tension between the imperative for international collaboration and the desire to preserve national autonomy and identity forms the core of contemporary geopolitical discourse, influencing debates on issues ranging from migration and environmental treaties to data privacy regulations and military alliances.`
    },
    '202': {
        title: "Decoupling and the Future of Globalization",
        content: `The economic doctrine of "decoupling" – the strategic disentanglement of national economies, particularly between major powers like the United States and China – has moved from theoretical debate to active policy consideration. Triggered by geopolitical rivalries, concerns over supply chain resilience, and national security anxieties regarding critical technologies, this trend marks a potential reversal of the globalization that defined the late 20th and early 21st centuries. Proponents argue that decoupling is necessary to reduce strategic dependencies, protect intellectual property, and bolster domestic industries in key sectors such as semiconductors, pharmaceuticals, and rare earth minerals.\n\nHowever, a nuanced analysis reveals that full-scale decoupling is an economic fiction. The depth of existing integration, characterized by complex, multi-tiered supply chains, makes a clean separation prohibitively expensive and logistically chaotic. A more probable and already unfolding scenario is "derisking," a targeted approach focused on limiting dependencies in a handful of strategically sensitive areas while maintaining robust trade and investment flows in others. For instance, a country might restrict foreign investment in its artificial intelligence or quantum computing sectors while continuing to import consumer electronics or agricultural products freely.\n\nThe long-term implications of this selective disentanglement are multifaceted. Economically, it could lead to inefficiencies, higher costs for consumers and businesses (a phenomenon often termed "greenflation" or "security inflation"), and a fragmentation of global technological standards. Politically, it may solidify economic blocs aligned with competing geopolitical spheres of influence. Ultimately, the decoupling debate underscores a fundamental recalibration: nations are increasingly prioritizing economic security and strategic autonomy over the pure efficiency gains that fueled the previous era of hyper-globalization. The challenge for policymakers is to navigate this shift without triggering a full-blown, mutually detrimental economic conflict.`
    },
    '203': {
        title: "Modern Conflict in the Information Age",
        content: `Military historians often categorize warfare into distinct "generations," delineating evolutionary leaps in tactics, technology, and the character of conflict. The widely cited framework describes a progression from massed manpower (1st Generation) through firepower and attrition (2nd), maneuver warfare (3rd), to the asymmetric and networked conflict of non-state actors (4th). In contemporary discourse, a vigorous debate centers on whether we are now witnessing the emergence of a "Fifth Generation Warfare" (5GW).\n\nProponents of the 5GW concept argue that the very nature of the battlefield has dissolved. They posit that modern conflict is dominated by non-kinetic, informational, and cognitive dimensions, where the primary objectives are to manipulate the adversary's perception, decision-making, and social cohesion. Key tools include sophisticated cyber operations, pervasive disinformation campaigns, economic coercion, and the weaponization of social media to create societal division and erode trust in institutions. In this view, a successful 5GW campaign could achieve strategic objectives without firing a single shot, by crippling an enemy from within.\n\nSkeptics, however, challenge the utility of this new generational label. They contend that many described 5GW tactics are merely modern iterations of age-old strategies of deception, subversion, and political warfare, now amplified by new technology. They warn that an overemphasis on this nebulous concept risks diverting attention and resources from the enduring realities of combined arms warfare, territorial defense, and the potential for high-intensity kinetic conflict, which remains a definitive element of state power. The debate, therefore, is not merely academic; it directly influences defense budgeting, force structure design, and the training of military personnel, forcing institutions to balance preparation for invisible, pervasive threats with readiness for traditional combat.`
    },
    '204': {
        title: "The Paradox of Sovereignty in Global Governance",
        content: `Global governance in the 21st century presents a complex paradox. The need for multilateral cooperation is escalating to address pressing transnational challenges—such as climate change, pandemics, and cybersecurity—at a time when nationalistic tendencies and assertions of state sovereignty are intensifying. These challenges have effectively led to an erosion of the concept of absolute sovereignty as defined by the Westphalian system, where domestic decisions are now significantly influenced by variables outside a state’s direct control. However, the existing international institutions, whose foundational rules were established in the mid-20th century, suffer from structural inertia that impedes their capacity to respond effectively to the speed and complexity of the evolving global landscape.\n\nMany analysts suggest that the lack of consensus regarding the reform of the UN Security Council, and the increasing use of the veto power, is not merely a procedural disagreement; it is a reflection of major powers’ reluctance to relinquish their privileges in favor of a more representative and equitable structure. This inertia has created "Grey Zones" filled by non-governmental initiatives or temporary regional coalitions attempting to fill the vacuum, which often results in scattered efforts instead of cohesive integration. The fundamental question facing the international system now is: Can the concept of Flexible Sovereignty, which involves a partial delegation to supranational organizations in specific domains, offer a compromise? Or are we inevitably heading towards a world dominated by narrow self-interests, where global solidarity becomes increasingly ineffective? The answer lies in the ability of leaders to move beyond zero-sum thinking.`
    },
    '205': {
        title: "The Digital Shift and the Call for a New Social Contract",
        content: `The latest wave of automation and Artificial Intelligence has imposed profound challenges on economic and social structures built over decades, subjecting the traditional notion of the "Social Contract" to intense scrutiny. The risk is no longer limited merely to the loss of routine jobs but lies in a fundamental alteration of the nature of work itself, creating a significant bifurcation in the labor market. This split divides workers into an upper tier of highly skilled professionals in technology and analysis, and a lower tier of workers in low-wage personal services that are difficult to automate. Consequently, the middle class, which traditionally anchored social stability, is eroding.\n\nThis widening gap places immense fiscal strain on existing financial and tax systems. As the base of fixed-wage employment shrinks and the proportion of the precarious Gig Economy rises, traditional tax revenues dwindle, while demands on social safety nets simultaneously escalate. Radical proposals have emerged to address this predicament, most notably the Universal Basic Income (UBI), viewed by some as a necessary response to the volatility of the automated job market. However, the debate surrounding UBI is deeply contentious: is it an effective stimulus for consumption and a mechanism for wealth redistribution, or could it exacerbate the issue of part-time employment and undermine the value of work as a core element of human dignity? The need for "lifelong learning" is no longer a pedagogical slogan but an urgent economic necessity for individuals to remain competitive, requiring massive governmental investments and a radical overhaul of educational curricula still dependent on pre-digital revolution models.`
    },
    '206': {
        title: "Hybrid Warfare and the Shifting Dynamics of Deterrence",
        content: `The contemporary security landscape is increasingly defined by "hybrid warfare," a strategy that blends conventional military force with irregular tactics, cyberattacks, and influence operations to achieve political objectives while remaining below the threshold of open, large-scale armed conflict. Unlike traditional warfare, which seeks a decisive victory on a physical battlefield, hybrid warfare targets the societal vulnerabilities of an adversary, aiming to undermine public trust, exacerbate social divisions, and paralyze decision-making processes. This ambiguity challenges classical theories of deterrence, which were primarily designed to prevent overt aggression through the threat of massive retaliation. In the hybrid realm, identifying the perpetrator and establishing a clear causal link between an action and its consequences is often difficult, making it harder to mount a proportionate and timely response.\n\nStrategists argue that countering hybrid threats requires a "whole-of-society" approach that goes beyond military capabilities. This includes bolstering cybersecurity across critical infrastructure, enhancing media literacy to combat disinformation, and strengthening the resilience of democratic institutions. Furthermore, international legal frameworks, largely developed in an era of clear distinctions between war and peace, are struggling to keep pace with these evolving methods. The lack of consensus on what constitutes an "act of war" in the digital or cognitive domains creates "gray zones" that adversaries can exploit. As nations adapt to this reality, the focus of national security is shifting from purely defensive posture to proactive resilience, emphasizing the need to detect and mitigate subtle forms of aggression before they escalate into systemic crises.`
    },
    '207': {
        title: "The Weaponization of Space and Orbital Stability",
        content: `As space becomes increasingly integral to modern communications, navigation, and military operations, the potential for its weaponization has become a critical concern for global security. The historical norm of space as a "global commons" for peaceful exploration is under threat from the development of anti-satellite (ASAT) weapons, orbital interceptors, and electronic warfare capabilities designed to disrupt or destroy space-based assets. This shift is driven by the strategic reality that modern militaries are deeply dependent on satellites for everything from precision targeting to real-time intelligence gathering, making these assets highly attractive targets in a potential conflict. However, the consequences of space-based conflict would be catastrophic and indiscriminate, potentially leading to the Kessler Syndrome—a scenario where a single collision creates a cascade of debris that renders certain orbits unusable for generations.\n\nExisting international law, primarily the 1967 Outer Space Treaty, prohibits the placement of weapons of mass destruction in orbit but remains vague on conventional weapons and ground-based ASAT systems. This legal ambiguity, combined with a lack of transparency and trust between major spacefaring nations, has fueled a burgeoning space arms race. Diplomatic efforts to establish "norms of responsible behavior" in space aim to reduce the risk of miscalculation and prevent the escalation of tensions. Proponents of these norms argue that maintaining orbital stability is a shared interest, as even a localized conflict in space would disrupt the global economy and hinder scientific progress for all. The challenge lies in balancing legitimate national security requirements with the collective imperative to preserve space as a safe and sustainable environment for future generations.`
    },
    '208': {
        title: "Supply Chain Resilience and Geoeconomic Imperatives",
        content: `The global economy is undergoing a fundamental shift as nations prioritize "supply chain resilience" over the pure cost-efficiency models that characterized previous decades of globalization. Recent global shocks, including the COVID-19 pandemic, geopolitical tensions, and climate-related disruptions, have exposed the fragility of lean, "just-in-time" manufacturing processes that rely on distant and often concentrated sources of production. This realization has sparked a move toward "friend-shoring," "near-shoring," and "reshoring," as countries seek to secure access to critical components such as semiconductors, batteries, and pharmaceutical ingredients. This trend is not merely economic but deeply geoeconomic, as trade relationships are increasingly viewed through the lens of national security and strategic autonomy.\n\nHowever, diversifying supply chains is a complex and costly endeavor that involves significant trade-offs. Building redundant capacity and establishing domestic production facilities requires massive capital investment and can lead to higher consumer prices. Furthermore, the high degree of specialization in modern manufacturing means that complete self-sufficiency is often unattainable, even for large economies. Critics warn that a fragmented global trade system could lead to inefficiencies and stifle innovation by limiting the scale of markets. The challenge for policymakers is to identify truly strategic vulnerabilities without sliding into broad protectionism. Establishing resilient supply chains requires a delicate balance between market-driven efficiency and state-led intervention, alongside deeper cooperation among allied nations to ensure collective economic security in an increasingly volatile global environment.`
    },
    '209': {
        title: "Soft Power and Information Warfare in the Digital Age",
        content: `The concept of "soft power"—the ability of a nation to influence others through attraction and persuasion rather than coercion—has been radically transformed by the digital revolution. In the past, soft power was largely projected through cultural exports, educational exchanges, and diplomatic outreach. Today, however, the digital landscape has become a primary arena for soft power competition, but it has also blurred the lines between legitimate public diplomacy and coercive "information warfare." The same platforms that allow for the global spread of ideas are also being used by state and non-state actors to conduct sophisticated disinformation campaigns, manipulate public opinion, and erode the social fabric of adversaries. This "weaponization of information" represents a significant challenge to the traditional understanding of how nations project influence.\n\nIn this environment, the credibility and perceived legitimacy of a nation's message are more important than ever. While authoritarian regimes may use centralized control to project a unified narrative, democratic societies often struggle with the openness that makes them vulnerable to foreign interference. However, some argue that this very openness can be a source of long-term soft power if it fosters genuine innovation, diverse cultural expression, and a resilient public sphere. The effectiveness of soft power in the 21st century depends on a nation's ability to navigate the complexities of the digital ecosystem, countering malicious narratives while authentically communicating its values. The battle for influence is no longer just about who has the best story, but about who can maintain the trust of a global audience in an era of "post-truth" politics and deepfakes.`
    },
    '210': {
        title: "Autonomous Weapon Systems and Meaningful Human Control",
        content: `The development of Lethal Autonomous Weapon Systems (LAWS)—often referred to as "killer robots"—represents one of the most controversial shifts in modern military technology. These systems, powered by artificial intelligence, are capable of selecting and engaging targets without direct human intervention. Proponents argue that LAWS could increase military efficiency, reduce casualties among one's own forces, and potentially be more precise than human operators in complex environments, thereby reducing collateral damage. They suggest that AI can process vast amounts of data and make decisions at speeds far exceeding human capability, which is becoming a necessity in the face of high-speed, networked warfare.\n\nHowever, the prospect of delegating the decision to kill to an algorithm raises profound ethical, legal, and strategic concerns. Critics emphasize the "responsibility gap"—the difficulty of holding anyone accountable for a war crime committed by an autonomous system. There are also fears about the "predictability" of AI in unpredictable combat situations, where unforeseen interactions could lead to unintended escalation. A central point of the international debate is the concept of "meaningful human control," with many nations and advocacy groups calling for a legal requirement that humans remain central to the decision-making process for the use of force. The challenge lies in defining what constitutes "meaningful" in a world where AI is increasingly integrated into every aspect of military operations. As the technology advances faster than international law can adapt, the debate over LAWS underscores the urgent need for new ethical frameworks and arms control agreements to prevent an uncontrolled and destabilizing AI arms race.`
    },
    '211': {
        title: "The Arctic Frontier: Geopolitical Competition in a Melting World",
        content: `The Arctic, once a peripheral region of limited strategic interest, is rapidly emerging as a central arena for geopolitical competition. As climate change causes Arctic ice to melt at an unprecedented rate, new shipping routes—such as the Northern Sea Route and the Northwest Passage—are becoming viable, potentially revolutionizing global trade by significantly shortening the journey between Asia and Europe. Furthermore, the region is estimated to contain vast untapped reserves of oil, natural gas, and critical minerals, sparking a race for resource extraction among Arctic nations and even non-Arctic actors like China, which has declared itself a "near-Arctic state." This scramble for influence and resources is putting strain on the long-standing cooperation that has characterized Arctic governance.\n\nThe strategic importance of the Arctic is also reflected in increased military activity. Arctic nations are modernizing their northern fleets, building new bases, and conducting large-scale exercises, raising concerns about a potential militarization of the region. The Arctic Council, the primary forum for regional cooperation, focuses on environmental protection and sustainable development but intentionally excludes hard security issues from its mandate. This creates a diplomatic vacuum where tensions over sovereignty, maritime boundaries, and resource rights could escalate. The challenge for the international community is to preserve the Arctic as a "zone of peace and low tension" while navigating the complex realities of environmental change and intensifying strategic rivalry. Achieving this will require a renewed commitment to international law, particularly the UN Convention on the Law of the Sea, and the development of new mechanisms for security dialogue in the High North.`
    },
    '212': {
        title: "Resource Scarcity and the Water-Energy-Food Nexus",
        content: `The global community is increasingly confronted by the "water-energy-food nexus," a framework that highlights the deep interdependencies between three of the world's most critical resources. As the global population grows and consumption patterns shift, the demand for all three is projected to rise significantly, creating potential for systemic scarcity. Water is essential for both food production (irrigation) and energy generation (cooling for power plants, hydropower), while energy is required for water treatment, desalination, and the production and transport of food. This interconnectedness means that a disruption or shortage in one area can have immediate and cascading effects across the others, potentially leading to social unrest, economic instability, and even conflict.\n\nClimate change acts as a "threat multiplier" in this nexus, altering precipitation patterns, increasing the frequency of droughts and floods, and threatening agricultural productivity. In many parts of the world, transboundary water resources are becoming a source of friction, as upstream countries build dams that affect the water security of downstream neighbors. Furthermore, the transition to renewable energy, while necessary for climate mitigation, also has implications for the nexus, as some bioenergy crops require significant water and land resources that could otherwise be used for food. Managing these competing demands requires integrated policy-making that moves beyond "siloed" approaches. Solutions must include investments in resource-efficient technologies, such as precision agriculture and advanced water recycling, as well as the development of robust international agreements for the shared management of resources. The ability to navigate the water-energy-food nexus will be a defining challenge for sustainable development and global security in the coming decades.`
    },
    '213': {
        title: "Digital Authoritarianism and Surveillance Capitalism",
        content: `The rise of "digital authoritarianism" represents a significant shift in how some states use technology to maintain political control and suppress dissent. By leveraging advanced surveillance tools, facial recognition, and data analytics, these regimes can monitor the activities and even the thoughts of their citizens with unprecedented precision. This goes beyond traditional censorship, creating a pervasive environment of digital monitoring where any perceived opposition can be identified and neutralized before it gains momentum. The export of these technologies to other countries is also raising concerns about the global spread of illiberal governance models. This trend is further complicated by the concept of "surveillance capitalism," where private companies collect and monetize vast amounts of personal data, often creating the very tools and infrastructures that authoritarian states exploit.\n\nIn democratic societies, the tension between security and privacy is at the heart of the debate over technology. While data collection can be used for legitimate purposes like public health or crime prevention, the lack of robust regulations and oversight can lead to abuses. The blurring of lines between state surveillance and corporate data mining creates a "surveillance industrial complex" that can undermine democratic norms and individual autonomy. Critics argue that the commodification of personal information has created a system where people are constantly nudged and manipulated by algorithms, eroding their capacity for independent judgment. Addressing these challenges requires a multifaceted approach, including the strengthening of data privacy laws, the promotion of encryption and other privacy-enhancing technologies, and the establishment of international norms to prevent the misuse of digital tools for political repression. The future of global democracy may depend on the ability to reclaim the digital sphere as a space for genuine freedom and empowerment.`
    },
    '214': {
        title: "Non-State Actors and the Erosion of the Monopoly on Violence",
        content: `A cornerstone of the modern state system, as defined by the Westphalian model, is the state's "monopoly on the legitimate use of physical force." However, in the 21st century, this monopoly is increasingly being challenged by a diverse array of non-state actors (NSAs), ranging from transnational terrorist organizations and powerful drug cartels to private military companies (PMCs) and decentralized hacker collectives. The proliferation of low-cost, high-impact technologies—such as drones, encryption, and cyber-weapons—has "democratized" the means of violence and disruption, allowing small groups or even individuals to project power on a global scale. This shift has profound implications for international security and the traditional role of the state as the primary provider of safety and order.\n\nIn many fragile states, NSAs have filled the vacuum left by weak or corrupt governance, providing services and security to local populations while simultaneously undermining the state's authority. This creates complex "hybrid" orders where the lines between legal and illegal, and public and private, are blurred. Furthermore, the increasing use of PMCs by major powers to conduct sensitive operations allows for "plausible deniability" and can complicate efforts at accountability. The rise of cyber-NSAs, such as "hacktivists" or state-sponsored proxies, adds another layer of complexity, as their actions can trigger real-world consequences without a clear physical origin. The international community is struggling to adapt to this new reality, as existing legal frameworks and diplomatic norms are primarily designed for state-to-state interactions. Addressing the challenges posed by non-state actors requires a recalibration of security strategies, emphasizing intelligence-sharing, international legal cooperation, and efforts to address the underlying drivers of state fragility that allow these actors to flourish.`
    },
    '215': {
        title: "Algorithmic Bias and the Ethics of AI Governance",
        content: `As Artificial Intelligence (AI) becomes increasingly integrated into critical decision-making processes—from hiring and lending to policing and judicial sentencing—the issue of "algorithmic bias" has emerged as a major ethical and social concern. These biases often stem from the data used to train AI models, which can reflect and even amplify existing human prejudices and historical inequalities. Because AI systems are often "black boxes" with opaque decision-making processes, it can be extremely difficult to identify, explain, or correct these biases, leading to outcomes that are discriminatory or unfair. This raises fundamental questions about accountability, transparency, and justice in the age of automation.\n\nThe challenge of AI governance is to create frameworks that encourage innovation while ensuring that these technologies are developed and used in a way that respects human rights and social equity. Some proponents of "ethical AI" call for rigorous auditing of algorithms, the use of diverse and representative datasets, and the inclusion of human-in-the-loop mechanisms for sensitive decisions. However, others warn that overly restrictive regulations could stifle progress and put certain countries at a competitive disadvantage. The global nature of AI development also means that national regulations may be insufficient, leading to calls for international standards and norms. Ultimately, the debate over AI governance is not just a technical one; it is a political and philosophical discussion about the kind of society we want to build. Ensuring that AI serves the public good will require a collaborative effort between technologists, policymakers, ethicists, and civil society to establish clear guidelines for the responsible and transparent use of this transformative technology.`
    },
    '216': {
        title: "Bio-Security and the Risks of Synthetic Biology",
        content: `The rapid advancement of synthetic biology—the ability to redesign organisms for useful purposes by engineering them to have new abilities—promises revolutionary breakthroughs in medicine, agriculture, and environmental protection. However, these same technologies also present significant "bio-security" risks. The increasing accessibility of powerful tools like CRISPR-Cas9, combined with the growing availability of genetic sequences online, has lowered the barriers for the creation of potentially harmful biological agents. This raises the specter of "dual-use" research, where scientific progress intended for good could be deliberately or accidentally repurposed for harm, such as the creation of more virulent pathogens or targeted bioweapons.\n\nThe global nature of biotechnology and the speed of innovation make it difficult for traditional regulatory frameworks to keep pace. Unlike nuclear technology, which requires massive infrastructure, high-end biology can be conducted in relatively small, decentralized laboratories, making monitoring and verification extremely challenging. This has led to calls for a new approach to bio-security that emphasizes "responsible stewardship," including more rigorous screening of DNA synthesis orders, enhanced oversight of high-risk research, and the promotion of ethical norms within the scientific community. Furthermore, the potential for accidental release of engineered organisms into the environment poses a unique challenge to global health and biodiversity. Strengthening international cooperation, such as through the Biological Weapons Convention, and investing in advanced detection and response capabilities are essential to mitigate these risks. The challenge is to foster a vibrant bio-economy while preventing the misuse of these powerful tools, a task that requires a delicate balance between scientific openness and the imperative for collective security.`
    },
    '217': {
        title: "Cognitive Warfare: The Battle for the Mind",
        content: `A new and deeply unsettling dimension of modern conflict is "cognitive warfare," which seeks to weaponize the human mind as a primary target. Unlike traditional information warfare, which focuses on controlling the flow of information, cognitive warfare aims to manipulate how people perceive, think, and react. By exploiting psychological vulnerabilities and biases—often through the use of AI-driven algorithms and big data—adversaries can influence the behavior of entire populations, erode social trust, and destabilize political systems from within. This is not just about spreading "fake news," but about a more profound and sustained effort to alter the very foundations of reality and identity for the target audience.\n\nThe tools of cognitive warfare are often subtle and pervasive, ranging from the micro-targeting of social media content to the use of deepfakes and the psychological manipulation of influential figures. This "invisible" form of aggression is particularly dangerous for democratic societies, which rely on an informed and cohesive citizenry for their functioning. Some experts argue that cognitive warfare should be recognized as a distinct domain of operations, alongside land, sea, air, space, and cyber. Defending against these threats requires more than just technical solutions; it requires "cognitive resilience"—enhancing the critical thinking skills of the public, promoting media literacy, and strengthening the social bonds that make a community resistant to manipulation. It also raises difficult questions about the ethics of psychological operations and the need for new international norms to protect the "cognitive sovereignty" of individuals and nations. As the boundary between the digital and physical worlds continues to blur, the battle for the mind may become the most consequential conflict of the 21st century.`
    },
    '218': {
        title: "Quantum Supremacy and the Future of Cryptography",
        content: `The quest for "quantum supremacy"—the point at which a quantum computer can perform a calculation that is impossible for a traditional supercomputer—is not just a scientific milestone but a major strategic imperative. While quantum computers promise to revolutionize fields like materials science, drug discovery, and optimization, they also pose an existential threat to modern cryptography. Most of the encryption that currently protects everything from personal messages and financial transactions to government secrets and military communications relies on mathematical problems that are easy for traditional computers to verify but incredibly difficult to solve. A sufficiently powerful quantum computer, however, could break these codes with ease, potentially rendering the world's digital infrastructure transparent and vulnerable.\n\nThis "quantum threat" has sparked an international race to develop "post-quantum cryptography" (PQC)—new encryption methods that are resistant to quantum attacks. This is a complex and urgent task, as the transition to new cryptographic standards will take years, if not decades, while data encrypted today could be "harvested" now and decrypted later by future quantum machines. Beyond security, quantum technology also has significant implications for sensing, navigation, and computing power, leading some to describe it as the "new oil" of the 21st century. Nations that lead in quantum development will gain a significant strategic and economic advantage, while those that fall behind may find their national security compromised. The challenge for the international community is to manage the transition to a quantum-ready world in a way that preserves stability and prevents a new, destabilizing technological arms race. This will require not only scientific innovation but also deep cooperation on standards, export controls, and the ethical use of this transformative technology.`
    },
    '219': {
        title: "Megacities and the Challenges of Urban Resilience",
        content: `The 21st century is the era of the "megacity"—vast, sprawling urban centers with populations exceeding ten million. This unprecedented urbanization is a global phenomenon, driven by economic opportunity, demographic shifts, and, increasingly, the displacement of people by environmental change. While megacities are engines of innovation and economic growth, they also concentrate risks and vulnerabilities on an immense scale. Providing essential services like water, energy, sanitation, and transportation to millions of people in a densely packed environment is a monumental logistical challenge, and the failure of any of these systems can quickly lead to a humanitarian and security crisis.\n\nClimate change poses a particularly acute threat to megacities, many of which are located in vulnerable coastal areas. Rising sea levels, more intense heatwaves, and extreme weather events can overwhelm urban infrastructure and lead to large-scale displacement and social unrest. Furthermore, the density and interconnectedness of megacities make them highly susceptible to the rapid spread of infectious diseases, as demonstrated by the COVID-19 pandemic. In many developing nations, the growth of megacities has outpaced the capacity of governments to provide formal housing and services, leading to the proliferation of informal settlements and "slums" that are often outside the reach of the state. Enhancing urban resilience requires a "smart city" approach that leverages technology and data for better management, but it also necessitates deep social and political reforms to ensure that the benefits of urbanization are shared equitably. The stability of the global system in the coming decades will increasingly depend on the ability of megacities to navigate the complex interplay of growth, sustainability, and security.`
    },
    '220': {
        title: "Deepfakes and the Geopolitics of Post-Truth",
        content: `The emergence of "deepfakes"—highly realistic and convincing synthetic media created using artificial intelligence—represents a significant escalation in the challenge of disinformation. While the technology has creative and benign applications, its potential for misuse in a geopolitical context is profound. Deepfakes can be used to create fake speeches by political leaders, simulate events that never happened, or manufacture compromising evidence to discredit individuals and institutions. This "weaponized reality" can be used to trigger social unrest, manipulate elections, or even provoke military conflict by providing a false "casus belli." The speed and ease with which deepfakes can be produced and disseminated through social media make them a particularly potent tool for state and non-state actors alike.\n\nBeyond the immediate impact of a specific fake, the proliferation of this technology contributes to a broader "post-truth" environment, where the very concept of objective reality is undermined. If anything can be faked, then everything—even authentic evidence—can be dismissed as fake. This "liar's dividend" benefits those who seek to evade accountability or sow confusion. Defending against deepfakes requires a combination of technical solutions, such as digital watermarking and AI-driven detection tools, and societal responses, like enhanced media literacy and a renewed commitment to institutional transparency. However, as the technology continues to improve, it may become increasingly difficult to distinguish between truth and fabrication. This raises fundamental questions about the future of public discourse and the nature of trust in a digitally mediated world. The ability of societies to develop a shared understanding of reality is essential for democratic governance and international stability, making the challenge of deepfakes one of the most pressing issues of the digital age.`
    },
    '221': {
        title: "The Circular Economy and Sustainability Transitions",
        content: `The transition from a traditional "linear" economy—characterized by a "take-make-dispose" model—to a "circular economy" is increasingly seen as an essential strategy for achieving global sustainability. A circular economy aims to decouple economic growth from resource consumption by designing out waste, keeping products and materials in use for as long as possible, and regenerating natural systems. This shift is driven by the growing realization that the earth's resources are finite and that the current model of production and consumption is placing unsustainable pressure on the planet's ecosystems, contributing to climate change, biodiversity loss, and resource scarcity. The circular approach is not just about recycling; it requires a fundamental rethink of business models, product design, and consumer behavior.\n\nImplementing a circular economy at scale is a complex challenge that involves significant structural and behavioral changes. It requires the development of new technologies for material recovery, the creation of robust markets for secondary materials, and the establishment of policies and regulations that incentivize circularity and penalize waste. For businesses, it may involve shifting from selling products to providing services (e.g., "lighting as a service" instead of selling lightbulbs). For consumers, it means moving away from a culture of disposable goods and toward one of repair, reuse, and sharing. While the transition offers significant economic opportunities—such as the creation of new industries and jobs—it also faces obstacles, including entrenched interests in the linear economy and the need for global cooperation to manage transboundary waste and material flows. The success of the circular economy will be a critical factor in the global effort to meet the Sustainable Development Goals and ensure a resilient and prosperous future within planetary boundaries.`
    },
    '222': {
        title: "The Outer Space Treaty and Legal Gaps in New Space",
        content: `The 1967 Outer Space Treaty (OST), which serves as the "constitution" for space law, was drafted in an era when space exploration was the exclusive domain of two superpowers and focused primarily on preventing the militarization of space. However, the emergence of the "New Space" era—characterized by the rapid commercialization of space, the involvement of a wide range of private actors, and the development of new technologies for resource extraction and orbital manufacturing—has exposed significant legal gaps in this foundational document. The OST's core principle that space is the "province of all mankind" and cannot be subject to national appropriation is increasingly at odds with the desire of private companies and some nations to claim ownership of space-based resources, such as water ice on the moon or minerals on asteroids.\n\nThis legal ambiguity creates uncertainty that could stifle investment and innovation, or worse, lead to conflict over competing claims. Recent national laws, such as the US Commercial Space Launch Competitiveness Act of 2015, have attempted to bridge this gap by granting private citizens the right to own and sell resources they extract in space, but these are not yet universally recognized or integrated into international law. Furthermore, the OST is vague on issues like space debris mitigation, the management of mega-constellations, and the activities of private military companies in orbit. Addressing these gaps requires a delicate diplomatic effort to modernize space law without undermining the peaceful principles of the OST. The challenge is to create a predictable and stable legal environment that encourages the sustainable development of space while ensuring that its benefits are shared equitably and that the orbital environment is preserved for future generations.`
    },
    '223': {
        title: "The Migrant Crisis and Global Demographic Shifts",
        content: `The world is currently witnessing levels of human displacement and migration that are unprecedented in modern history. This "migrant crisis" is driven by a complex interplay of factors, including violent conflict, political instability, economic inequality, and, increasingly, the impacts of climate change. While migration is an age-old phenomenon, the scale and speed of current movements are putting immense strain on the international refugee regime and the social and political fabric of both transit and host nations. In many parts of the world, migration has become a highly polarized political issue, fueling the rise of populism, nationalism, and calls for more restrictive border controls. This has created a significant tension between the humanitarian obligation to protect vulnerable people and the state's desire to control its borders and preserve social cohesion.\n\nBeyond the immediate crisis, the world is also undergoing a profound demographic shift. While many developed nations are facing aging populations and shrinking workforces, other parts of the world, particularly in Africa and South Asia, are experiencing a "youth bulge." These demographic imbalances create a powerful push-pull dynamic for migration that is likely to intensify in the coming decades. Managing this reality requires a move away from "crisis management" and toward a more comprehensive and sustainable global approach to migration. This includes addressing the root causes of displacement, such as conflict and poverty, as well as creating legal and safe pathways for migration that can benefit both migrants and their host communities. It also requires a renewed commitment to the principles of burden-sharing and international solidarity, as outlined in the Global Compact for Migration. The ability of the international community to manage migration humanely and effectively will be a key indicator of the health and resilience of the global order.`
    },
    '224': {
        title: "Central Bank Digital Currencies (CBDCs) and Global Finance",
        content: `The rise of cryptocurrencies and the increasing digitalization of payments have prompted central banks around the world to explore the creation of their own digital currencies—Central Bank Digital Currencies (CBDCs). Unlike decentralized cryptocurrencies like Bitcoin, CBDCs would be a digital form of a nation's sovereign currency, issued and regulated by the central bank. Proponents argue that CBDCs could enhance the efficiency and security of payment systems, promote financial inclusion by providing access to digital money for the unbanked, and improve the effectiveness of monetary policy by allowing for more direct and real-time interventions. In the international arena, a CBDC could also facilitate faster and cheaper cross-border transactions, potentially challenging the dominance of traditional systems like SWIFT.\n\nHowever, the introduction of CBDCs also raises significant concerns about privacy, financial stability, and the role of the state in the economy. Because a CBDC would allow the central bank to track every transaction, it could provide the state with unprecedented power to monitor and control the financial activities of its citizens, raising serious human rights and privacy issues. There are also fears that a poorly designed CBDC could lead to a "run on the banks" if people move their deposits from commercial banks to the central bank during a crisis, potentially destabilizing the entire financial system. Furthermore, the geopolitical implications of "digital currencies" are profound, as nations like China lead in the development of their own digital yuan, potentially creating a new financial architecture that bypasses the US-led system. The debate over CBDCs is not just about technology; it is about the future of money, the relationship between the individual and the state, and the shifting balance of power in the global financial system.`
    },
    '225': {
        title: "Climate Reparations and the Quest for Global South Justice",
        content: `The debate over "climate reparations"—more formally known as "loss and damage" in international negotiations—has become a central and deeply contentious issue in global climate politics. It is based on the argument that wealthy, industrialized nations, which are historically responsible for the majority of greenhouse gas emissions, have a moral and legal obligation to provide financial compensation and support to the vulnerable countries of the "Global South." These developing nations often contribute the least to climate change but suffer its most severe consequences, including rising sea levels, extreme weather events, and catastrophic crop failures. For many in the Global South, climate change is not just an environmental issue but a matter of historical injustice and a threat to their right to development.\n\nThe demand for climate reparations has long been resisted by developed nations, which fear that accepting liability could lead to endless legal claims and astronomical costs. However, the increasing frequency and severity of climate-related disasters have made the issue impossible to ignore. A significant milestone was reached at the COP27 summit with the agreement to establish a dedicated "Loss and Damage Fund," but many questions remain about who will contribute to the fund, how it will be managed, and how the money will be distributed. Beyond direct financial transfers, the debate also encompasses issues like debt relief, technology transfer, and support for "climate refugees." Achieving climate justice requires a fundamental shift in the relationship between the Global North and South, moving from a model of "aid" to one of "responsibility" and "solidarity." The ability of the international community to address the loss and damage issue fairly and effectively will be a critical test of the legitimacy and viability of the global climate regime.`
    },
    '226': {
        title: "The Great Reset and the Transformation of Global Capitalism",
        content: `The "Great Reset" is a concept popularized by the World Economic Forum (WEF) that calls for a fundamental reimagining of global social and economic systems in the wake of the COVID-19 pandemic. Its proponents argue that the pandemic has exposed the deep flaws and inequalities of the current model of capitalism, and that a "reset" is necessary to build a more sustainable, equitable, and resilient future. This vision includes a shift from "shareholder capitalism" to "stakeholder capitalism," where businesses prioritize the needs of their employees, customers, and the environment alongside profits. It also emphasizes the need for a "green recovery," with massive investments in renewable energy and sustainable infrastructure, and a more robust social safety net to address the challenges of the digital age.\n\nHowever, the Great Reset has also been met with significant criticism and skepticism. Some see it as an attempt by a global elite to impose a top-down, technocratic agenda that undermines national sovereignty and individual freedom. Critics warn that the push for more centralized global governance and the closer integration of state and corporate power could lead to a form of "corporatism" that stifles competition and limits democratic accountability. There are also concerns about the potential for "greenwashing," where companies use the language of sustainability to hide business-as-usual practices. The debate over the Great Reset reflects a broader struggle over the future of the global order. While there is a growing consensus that the current system is under strain, there is deep disagreement about the nature of the solution. The challenge is to find a path forward that addresses the urgent need for systemic change without compromising the values of openness, competition, and democratic choice.`
    },
    '227': {
        title: "Geoengineering: The Risks and Rewards of Climate Intervention",
        content: `As the world continues to struggle with reducing greenhouse gas emissions, interest is growing in "geoengineering"—large-scale, intentional interventions in the Earth's climate system to counteract the effects of global warming. These technologies fall into two main categories: Solar Radiation Management (SRM), which aims to reflect a small percentage of sunlight back into space (e.g., by injecting aerosols into the stratosphere), and Carbon Dioxide Removal (CDR), which seeks to remove CO2 directly from the atmosphere. While some scientists and policymakers view geoengineering as a necessary "plan B" or an insurance policy in case of climate catastrophe, others warn that it is an extremely risky and unpredictable endeavor that could have unintended and potentially devastating consequences for the global environment and security.\n\nThe risks of geoengineering are numerous and complex. SRM, for example, could alter global precipitation patterns, potentially causing droughts in some regions while increasing floods in others. There is also the "termination shock" risk—if an SRM system were suddenly stopped, the temperature could rise at a rate far faster than ecosystems and societies could adapt to. Furthermore, the ability of a single nation or even a wealthy individual to "go it alone" and deploy geoengineering technology raises profound questions about global governance and the potential for conflict over who "controls the thermostat" of the planet. Critics also argue that the prospect of a technical "fix" could create a "moral hazard," reducing the urgency for the deep structural changes needed to decarbonize the economy. Establishing international norms and a robust legal framework for the research and potential deployment of geoengineering is an urgent task for the global community to prevent a chaotic and destabilizing climate intervention.`
    },
    '228': {
        title: "The Post-Pandemic Order and Global Systemic Shifts",
        content: `The COVID-19 pandemic has been a "systemic shock" that has accelerated many of the trends already reshaping the global order, while also creating entirely new challenges. It has exposed the vulnerabilities of an hyper-globalized world, the fragility of international institutions, and the deep inequalities within and between nations. As the world moves into a "post-pandemic" era, it is clear that there will be no return to the "old normal." Instead, we are seeing a shift toward a more fragmented and competitive international system, where the balance of power is increasingly fluid and the traditional distinctions between security, economics, and health are blurred. The pandemic has also intensified the rivalry between major powers, particularly the US and China, while simultaneously highlighting the need for collective action on global threats.\n\nOne of the most significant shifts is the renewed role of the state in the economy and society. Governments have taken on unprecedented powers to protect public health and support their economies, leading to a debate over the long-term implications for individual liberty and fiscal sustainability. There is also a move toward "sovereign resilience," as nations seek to reduce their dependencies on foreign supply chains for critical goods. At the same time, the pandemic has accelerated the digital transformation of every aspect of life, from work and education to healthcare and governance, creating new opportunities but also deepening the digital divide. The future of the global order will depend on whether nations can find new ways to cooperate in an increasingly divided world, and whether the lessons of the pandemic can be used to build a more resilient and equitable international system. The challenge is to navigate this period of "poly-crisis" without losing sight of the long-term goals of peace, sustainability, and human dignity.`
    }
};

// الجزء الأخير الخاص بالكلمات (Terms) إذا كنت تريدها مفصولة
const termsList = {
    '201': [
        { id: 't1', english: 'Multilateral', arabic: 'متعدد الأطراف' },
        { id: 't2', english: 'Cede', arabic: 'يتنازل عن' },
        { id: 't3', english: 'Transnational', arabic: 'عابر للحدود الوطنية' },
        { id: 't4', english: 'Pragmatic', arabic: 'براغماتي / واقعي' }
    ],
    // يمكن إضافة بقية الكلمات هنا تباعاً
};
