window.levels = [
  { id: "beginner", name: "المستوى المبتدئ", icon: "🌱" },
  { id: "intermediate", name: "المستوى المتوسط", icon: "🌿" },
  { id: "advanced", name: "المستوى المتقدم", icon: "🌳" }
];

window.lessonsList = {
  "beginner": [
    { id: "1", title: "1. Greetings and Introductions" },
    { id: "2", title: "2. Numbers 1-10"},
    { id: "3", title: "3. Colors" },
    { id: "4", title: "4. Family Members" },
    { id: "5", title: "5. Things at Home" },
    { id: "6", title: "6. Days and Months" },
    { id: "7", title: "7. Feelings"},
    { id: "8", title: "8. Clothes" },
    { id: "9", title: "9. Animals" },
    { id: "10", title: "10. Food and Drink" },
    { id: "11", title: "11. Daily Routines"},
    { id: "12", title: "12. Common Verbs" },
    { id: "13", title: "13. Simple Adjectives" },
    { id: "14", title: "14. Telling Time" },
    { id: "15", title: "15. At School"},
    { id: "16", title: "16. Places in Town" },
    { id: "17", title: "17. Transportation" },
    { id: "18", title: "18. Weather and Seasons" },
    { id: "19", title: "19. Hobbies"},
    { id: "20", title: "20. Sports" },
    { id: "21", title: "21. Past Tense - Regular Verbs" },
    { id: "22", title: "22. Past Tense - Irregular Verbs" },
    { id: "23", title: "23. Future with Will" },
    { id: "24", title: "24. Prepositions of Place" },
    { id: "25", title: "25. Linking Words" },
    { id: "26", title: "26. Personal Introduction" },
    { id: "27", title: "27. Adam and His Friend" },
    { id: "28", title: "28. Adam's Morning Routine" },
    { id: "29", title: "29. Adam at School" },
    { id: "30", title: "30. Adam at the Café" },
    { id: "31", title: "31. Adam’s Family" },
    { id: "32", title: "32. Shopping Day" },
    { id: "33", title: "33. Adam's Hobby" },
    { id: "34", title: "34. A Rainy Day" },
    { id: "35", title: "35. Helping a Neighbor" },
    { id: "36", title: "36. A Busy Morning" },
    { id: "37", title: "37. At the Library" },
    { id: "38", title: "38. A Phone Call" },
    { id: "39", title: "39. At the Doctor" },
    { id: "40", title: "40. A Small Trip" },
    { id: "41", title: "41. A New Classmate" },
    { id: "42", title: "42. A School Project" },
    { id: "43", title: "43. A Visit to the Park" },
    { id: "44", title: "44. A Problem at Home" },
    { id: "45", title: "45. Looking to the Future" },
    { id: "46", title: "46. A Weekend at the Beach" },
    { id: "47", title: "47. A Visit to the Museum" },
    { id: "48", title: "48. Cooking a Traditional Meal" },
    { id: "49", title: "49. A Day at the Zoo" },
    { id: "50", title: "50. Life in a Big City" },
    { id: "51", title: "51. Learning a New Language" },
    { id: "52", title: "52. The Importance of Daily Exercise" },
    { id: "53", title: "53. A Trip to the Countryside" },
    { id: "54", title: "54. Technological Advancements in Daily Life" },
    { id: "55", title: "55. The Joy of Volunteering" },
    { id: "56", title: "56. Planning a Career" },
    { id: "57", title: "57. Cultural Festivals Around the World" },
    { id: "58", title: "58. The Benefits of Reading" },
    { id: "59", title: "59. Navigating an International Airport" },
    { id: "60", title: "60. Environmental Protection" }
  ],
  "intermediate": [
    { id: "61", title: " A Surprise Celebration" },
    { id: "62", title: " Renting an Apartment" },
    { id: "63", title: " Learning a Musical Instrument" },
    { id: "64", title: " A Visit to a Science Center" },
    { id: "65", title: " Remote Work Challenges" },
    { id: "66", title: " Digital Citizenship" },
    { id: "67", title: " Artificial Intelligence" },
    { id: "68", title: " Space Exploration" },
    { id: "69", title: " Renewable Energy" },
    { id: "70", title: " Emotional Intelligence" },
    { id: "71", title: " Global Warming" },
    { id: "72", title: " Healthy Cooking" },
    { id: "73", title: " Modern Architecture" },
    { id: "74", title: " History of the Internet" },
    { id: "75", title: " Urban Planning" },
    { id: "76", title: "  " },
    { id: "77", title: "  " },
    { id: "78", title: "  " },
    { id: "79", title: "  " },
    { id: "80", title: "  " },
    { id: "81", title: "  " },
    { id: "82", title: "  " },
    { id: "83", title: "  " },
    { id: "84", title: "  " },
    { id: "85", title: "  " },
    { id: "86", title: "  " },
    { id: "87", title: "  " },
    { id: "88", title: "  " },
    { id: "89", title: "  " },
    { id: "90", title: "  " }
  ],
  "advanced": [
    { id: "301", title: "Cooperative Sovereignty in a Globalized Era" },
    { id: "302", title: "Decoupling and the Future of Globalization" },
    { id: "303", title: "Modern Conflict in the Information Age" },
    { id: "304", title: "The Paradox of Sovereignty in Global Governance" },
    { id: "305", title: "The Digital Shift and the Call for a New Social Contract" },
    { id: "306", title: "The Shifting Dynamics of Deterrence in the Age of Hybrid Warfare" },
    { id: "307", title: " The Weaponization of Space and the Challenge to Orbital Stability" },
    { id: "308", title: "Geoeconomics and the New Imperatives of Supply Chain Resilience" },
    { id: "309", title: " Soft Power, Digital Diplomacy, and the Counter-Strategy of Information Warfare" },
    { id: "310", title: "Autonomous Weapon Systems and the Principle of Meaningful Human Control" },
    { id: "311", title: "The Efficacy and Ethics of Large-Scale Infrastructure Financing" },
    { id: "312", title: "The Fragmentation of the Public Sphere and Epistemological Isolation" },
    { id: "313", title: "The Erosion of Multilateralism and the Rise of Strategic Hedging" },
    { id: "314", title: "The Paradox of Digitalization and Labor Productivity" },
    { id: "315", title: "The Strategic Implications of Hypersonic Weapons" },
    { id: "316", title: "Digital Sovereignty: A New Frontier in Geopolitical Competition" },
    { id: "317", title: " The Unintended Consequences of Unconventional Monetary Policy" },
    { id: "318", title: "The Autonomy Dilemma: Ethical and Legal Quandaries of Lethal Autonomous Weapon Systems" },
    { id: "319", title: " Modern Public Transportation Systems" },
    { id: "320", title: " History and Evolution of the Internet" },
    { id: "321", title: " Modern Architecture and Smart Cities" },
    { id: "322", title: " Healthy Eating Habits and Home Cooking" },
    { id: "323", title: " Global Warming and Environmental Challenges" },
    { id: "324", title: " The Psychology of Emotional Intelligence" },
    { id: "325", title: " The Rise of Renewable Energy Entrepreneurship" },
    { id: "326", title: " Space Exploration and the Future of Humanity" },
    { id: "327", title: " Artificial Intelligence and the Future of Work" },
    { id: "328", title: " Digital Citizenship and Online Safety" }
  ]
};

window.lessonsData = {
  "1": {
    "title": "Greetings and Introductions",
    "content": "Hello! Good morning. How are you? I'm fine, thank you. This is my friend. What is your name? My name is Adam. Nice to meet you. See you later! Goodbye!",
    "terms": [
      {"id": "1-1", "english": "Hi", "arabic": "مرحباً (غير رسمي)"},
      {"id": "1-2", "english": "Good morning", "arabic": "صباح الخير"},
      {"id": "1-3", "english": "Good afternoon", "arabic": "مساء الخير (بعد الظهر)"},
      {"id": "1-4", "english": "Good evening", "arabic": "مساء الخير"},
      {"id": "1-5", "english": "Good night", "arabic": "تصبح على خير"},
      {"id": "1-6", "english": "See you later", "arabic": "أراك لاحقاً"},
      {"id": "1-7", "english": "Welcome", "arabic": "أهلاً وسهلاً"},
      {"id": "1-8", "english": "How are you?", "arabic": "كيف حالك؟"},
      {"id": "1-9", "english": "I'm fine", "arabic": "أنا بخير"},
      {"id": "1-10", "english": "Thank you", "arabic": "شكراً لك"}
    ]
  },
  // ... باقي الدروس (2 إلى 328) بنفس المحتوى الأصلي ...
  // تم حذف الجزء الأوسط للاختصار، ولكن في الملف النهائي سيكون كاملاً
  "328": {
    "title": "Digital Citizenship and Online Safety",
    "content": "In an era where our personal and professional lives are increasingly lived online, the concept of 'digital citizenship' has become more important than ever. Being a good digital citizen involves using technology responsibly, respectfully, and critically. As social media platforms continue to influence public opinion, it is crucial for individuals to develop strong media literacy skills to identify misinformation and 'fake news.' If we teach children about online etiquette and safety at a young age, they will be better prepared to navigate the complexities of the internet. One of the greatest risks in the digital world is cybercrime, which includes identity theft, phishing, and hacking. To protect sensitive information, experts recommend using multi-factor authentication and strong, unique passwords for every account. Furthermore, understanding the concept of a 'digital footprint' is essential; everything we post online leaves a permanent trace that can be seen by future employers or university admissions officers. Adam recently attended a webinar about cybersecurity and learned how to identify suspicious emails that often contain malicious attachments. He realized that a simple click on a dangerous link could compromise his entire network. Consequently, he has become more cautious about sharing personal details on public forums. Another important aspect of digital citizenship is combating cyberbullying. Protecting vulnerable users and promoting a culture of kindness is a shared responsibility of all internet users. Despite the convenience of being constantly connected, it is also important to practice 'digital detox' to maintain mental health and avoid screen addiction. By finding a balance between our virtual and physical lives, we can enjoy the benefits of technology without losing our sense of real-world connection and well-being.",
    "terms": [
      {"id": "328-1", "english": "Citizenship", "arabic": "مواطنة"},
      {"id": "328-2", "english": "Responsibly", "arabic": "بمسؤولية"},
      {"id": "328-3", "english": "Respectfully", "arabic": "باحترام"},
      {"id": "328-4", "english": "Critically", "arabic": "بشكل نقدي"},
      {"id": "328-5", "english": "Literacy", "arabic": "ثقافة/معرفة بالقراءة والكتابة"},
      {"id": "328-6", "english": "Misinformation", "arabic": "معلومات مضللة"},
      {"id": "328-7", "english": "Etiquette", "arabic": "إتيكيت/آداب السلوك"},
      {"id": "328-8", "english": "Cybercrime", "arabic": "جريمة إلكترونية"},
      {"id": "328-9", "english": "Identity theft", "arabic": "سرقة الهوية"},
      {"id": "328-10", "english": "Phishing", "arabic": "تصيد احتيالي"},
      {"id": "328-11", "english": "Hacking", "arabic": "اختراق"},
      {"id": "328-12", "english": "Sensitive", "arabic": "حساس"},
      {"id": "328-13", "english": "Authentication", "arabic": "مصادقة/توثيق"},
      {"id": "328-14", "english": "Digital footprint", "arabic": "بصمة رقمية"},
      {"id": "328-15", "english": "Permanent", "arabic": "دائم"},
      {"id": "328-16", "english": "Admissions", "arabic": "قبول (جامعي)"},
      {"id": "328-17", "english": "Webinar", "arabic": "ندوة عبر الإنترنت"},
      {"id": "328-18", "english": "Cybersecurity", "arabic": "الأمن السيبراني"},
      {"id": "328-19", "english": "Suspicious", "arabic": "مريب/مشكوك فيه"},
      {"id": "328-20", "english": "Malicious", "arabic": "خبيث (برمجيات)"},
      {"id": "328-21", "english": "Attachments", "arabic": "مرفقات"},
      {"id": "328-22", "english": "Compromise", "arabic": "يعرض للخطر/يخترق"},
      {"id": "328-23", "english": "Cautious", "arabic": "حذر"},
      {"id": "328-24", "english": "Forums", "arabic": "منتديات"},
      {"id": "328-25", "english": "Cyberbullying", "arabic": "تنمر إلكتروني"},
      {"id": "328-26", "english": "Vulnerable", "arabic": "عرضة للأذى/ضعيف"},
      {"id": "328-27", "english": "Detox", "arabic": "تخلص من السموم (رقمي)"},
      {"id": "328-28", "english": "Virtual", "arabic": "افتراضي"},
      {"id": "328-29", "english": "Era", "arabic": "عصر/عهد"},
      {"id": "328-30", "english": " literacy", "arabic": "ثقافة"},
      {"id": "328-31", "english": "Permanent", "arabic": "دائم"},
      {"id": "328-32", "english": "Trace", "arabic": "أثر"},
      {"id": "328-33", "english": "Dangerous", "arabic": "خطير"},
      {"id": "328-34", "english": "Connected", "arabic": "متصل"},
      {"id": "328-35", "english": "Combating", "arabic": "مكافحة"},
      {"id": "328-36", "english": "Kindness", "arabic": "لطف"},
      {"id": "328-37", "english": "Addiction", "arabic": "إدمان"},
      {"id": "328-38", "english": "Sense", "arabic": "إحساس"},
      {"id": "328-39", "english": "Footprint", "arabic": "بصمة/أثر"},
      {"id": "328-40", "english": "Citizen", "arabic": "مواطن"}
    ]
  }
};

window.placementBank = {
  "A1": [  
    {"q": "She ___ a doctor.", "options": ["am", "is", "are"], "correct": "is"},
    {"q": "They ___ from Spain.", "options": ["is", "am", "are"], "correct": "are"},
    {"q": "I ___ a student.", "options": ["am", "is", "are"], "correct": "am"},
    {"q": "He ___ to school every day.", "options": ["go", "goes", "going"], "correct": "goes"},
    {"q": "We ___ like ice cream.", "options": ["don't", "doesn't", "not"], "correct": "don't"},
    {"q": "___ you like pizza?", "options": ["Does", "Do", "Are"], "correct": "Do"},
    {"q": "This is ___ apple.", "options": ["a", "an", "the"], "correct": "an"},
    {"q": "I have ___ car.", "options": ["a", "an", "the"], "correct": "a"},
    {"q": "The cat is ___ the table.", "options": ["on", "in", "at"], "correct": "on"},
    {"q": "She ___ reading a book.", "options": ["is", "am", "are"], "correct": "is"},
    {"q": "They ___ playing football.", "options": ["is", "am", "are"], "correct": "are"},
    {"q": "I ___ like coffee.", "options": ["don't", "doesn't", "not"], "correct": "don't"},
    {"q": "He ___ breakfast at 7 o'clock.", "options": ["have", "has", "having"], "correct": "has"},
    {"q": "We ___ to the park every Sunday.", "options": ["go", "goes", "going"], "correct": "go"},
    {"q": "She ___ her teeth every morning.", "options": ["brush", "brushes", "brushing"], "correct": "brushes"},
    {"q": "My name ___ Ahmed.", "options": ["is", "am", "are"], "correct": "is"},
    {"q": "I am ___ years old.", "options": ["ten", "ten years", "a ten"], "correct": "ten"},
    {"q": "This is my ___ .", "options": ["father", "fathers", "father's"], "correct": "father"},
    {"q": "The books are on ___ shelf.", "options": ["a", "an", "the"], "correct": "the"},
    {"q": "I ___ to music at night.", "options": ["listen", "listens", "listening"], "correct": "listen"},
    {"q": "He ___ a new phone.", "options": ["has", "have", "is"], "correct": "has"},
    {"q": "___ you speak English?", "options": ["Does", "Do", "Are"], "correct": "Do"},
    {"q": "Where ___ she live?", "options": ["do", "does", "is"], "correct": "does"},
    {"q": "I ___ like spicy food.", "options": ["don't", "doesn't", "not"], "correct": "don't"},
    {"q": "The children ___ playing outside.", "options": ["is", "am", "are"], "correct": "are"},
    {"q": "She ___ to work by bus.", "options": ["go", "goes", "going"], "correct": "goes"},
    {"q": "We are ___ the classroom.", "options": ["in", "on", "at"], "correct": "in"},
    {"q": "The sun ___ in the east.", "options": ["rise", "rises", "rising"], "correct": "rises"},
    {"q": "He ___ a glass of milk every night.", "options": ["drink", "drinks", "drinking"], "correct": "drinks"},
    {"q": "They ___ from London.", "options": ["comes", "come", "coming"], "correct": "come"},
    {"q": "I ___ a sister and two brothers.", "options": ["has", "have", "am"], "correct": "have"},
    {"q": "She ___ like apples.", "options": ["don't", "doesn't", "not"], "correct": "doesn't"},
    {"q": "The bag is ___ the chair.", "options": ["on", "under", "behind"], "correct": "under"},
    {"q": "___ colour is your car?", "options": ["What", "Which", "Who"], "correct": "What"},
    {"q": "It ___ a big house.", "options": ["is", "am", "are"], "correct": "is"} 
  ],
  "A2": [  
    {"q": "Yesterday, I ___ to the cinema.", "options": ["go", "went", "gone"], "correct": "went"},
    {"q": "She didn't ___ the answer.", "options": ["know", "knew", "known"], "correct": "know"},
    {"q": "We have ___ finished our homework.", "options": ["yet", "already", "still"], "correct": "already"},
    {"q": "He is ___ than his brother.", "options": ["taller", "tall", "more tall"], "correct": "taller"},
    {"q": "This is the ___ movie I've ever seen.", "options": ["good", "better", "best"], "correct": "best"},
    {"q": "They ___ living in Paris for two years.", "options": ["have been", "has been", "are"], "correct": "have been"},
    {"q": "I ___ to London next week.", "options": ["go", "will go", "went"], "correct": "will go"},
    {"q": "She can ___ French.", "options": ["speak", "to speak", "speaking"], "correct": "speak"},
    {"q": "___ I open the window?", "options": ["May", "Can", "Must"], "correct": "May"},
    {"q": "If it rains, we ___ at home.", "options": ["stay", "will stay", "would stay"], "correct": "will stay"},
    {"q": "He used to ___ swimming every day.", "options": ["go", "went", "going"], "correct": "go"},
    {"q": "I'm interested ___ learning Spanish.", "options": ["in", "on", "at"], "correct": "in"},
    {"q": "She is afraid ___ spiders.", "options": ["of", "from", "about"], "correct": "of"},
    {"q": "They arrived ___ the airport at 5 pm.", "options": ["at", "in", "to"], "correct": "at"},
    {"q": "I've lived here ___ 2010.", "options": ["since", "for", "from"], "correct": "since"},
    {"q": "She's worked here ___ five years.", "options": ["since", "for", "from"], "correct": "for"},
    {"q": "The car needs ___.", "options": ["wash", "to wash", "washing"], "correct": "washing"},
    {"q": "He told me ___ wait.", "options": ["to", "for", ""], "correct": "to"},
    {"q": "I enjoy ___ tennis.", "options": ["play", "to play", "playing"], "correct": "playing"},
    {"q": "She's the woman ___ works in the bank.", "options": ["who", "which", "where"], "correct": "who"},
    {"q": "This is the house ___ I was born.", "options": ["where", "which", "who"], "correct": "where"},
    {"q": "I don't have ___ money.", "options": ["much", "many", "a lot"], "correct": "much"},
    {"q": "How ___ apples do you want?", "options": ["much", "many", "a lot"], "correct": "many"},
    {"q": "He speaks English ___ .", "options": ["good", "well", "fine"], "correct": "well"},
    {"q": "She looked ___ she was tired.", "options": ["as if", "like", "as"], "correct": "as if"},
    {"q": "They ___ to the party last night.", "options": ["didn't come", "don't come", "not come"], "correct": "didn't come"},
    {"q": "I ___ my keys yesterday.", "options": ["have lost", "lost", "lose"], "correct": "lost"},
    {"q": "We ___ each other for ages.", "options": ["know", "have known", "are knowing"], "correct": "have known"},
    {"q": "The train ___ at 6 pm.", "options": ["leaves", "is leaving", "leave"], "correct": "leaves"},
    {"q": "Look! It ___ .", "options": ["rains", "is raining", "rain"], "correct": "is raining"},
    {"q": "She usually ___ early.", "options": ["wake up", "wakes up", "is waking up"], "correct": "wakes up"},
    {"q": "I promise I ___ you.", "options": ["won't tell", "don't tell", "not tell"], "correct": "won't tell"},
    {"q": "If I were you, I ___ a doctor.", "options": ["will see", "would see", "saw"], "correct": "would see"},
    {"q": "They ___ to the beach every summer.", "options": ["go", "went", "have gone"], "correct": "go"},
    {"q": "He's ___ to buy a new car.", "options": ["going", "will", "go"], "correct": "going"} 
  ],
  "B1": [  
    {"q": "If I ___ you, I would apologize.", "options": ["was", "were", "am"], "correct": "were"},
    {"q": "She ___ play the piano when she was five.", "options": ["can", "could", "may"], "correct": "could"},
    {"q": "They ___ finished the project by tomorrow.", "options": ["will have", "have", "had"], "correct": "will have"},
    {"q": "He asked where ___ from.", "options": ["I come", "do I come", "I came"], "correct": "I came"},
    {"q": "I'm not sure ___ to go.", "options": ["where", "which", "what"], "correct": "where"},
    {"q": "She ___ to the meeting, but she was ill.", "options": ["was going to come", "came", "had come"], "correct": "was going to come"},
    {"q": "You ___ wear a tie; it's casual.", "options": ["mustn't", "don't have to", "shouldn't"], "correct": "don't have to"},
    {"q": "He ___ be at home because the lights are off.", "options": ["must", "can't", "might"], "correct": "can't"},
    {"q": "I wish I ___ more time.", "options": ["have", "had", "would have"], "correct": "had"},
    {"q": "This is the man ___ helped us.", "options": ["who", "which", "whom"], "correct": "who"},
    {"q": "The film was ___ boring that I fell asleep.", "options": ["so", "such", "too"], "correct": "so"},
    {"q": "She speaks English ___ than me.", "options": ["good", "better", "best"], "correct": "better"},
    {"q": "By the time we arrived, they ___.", "options": ["left", "have left", "had left"], "correct": "had left"},
    {"q": "I'm used to ___ up early.", "options": ["get", "getting", "got"], "correct": "getting"},
    {"q": "He advised me ___ the red dress.", "options": ["buy", "to buy", "buying"], "correct": "to buy"},
    {"q": "If it ___ tomorrow, we'll cancel the picnic.", "options": ["rains", "will rain", "rained"], "correct": "rains"},
    {"q": "She ___ have left; her coat is here.", "options": ["must", "can't", "should"], "correct": "can't"},
    {"q": "You ___ see the doctor if you feel worse.", "options": ["should", "would", "might"], "correct": "should"},
    {"q": "He said he ___ help me.", "options": ["will", "would", "can"], "correct": "would"},
    {"q": "They ___ live in London before moving here.", "options": ["used to", "would", "were used to"], "correct": "used to"},
    {"q": "I don't mind ___ late.", "options": ["work", "to work", "working"], "correct": "working"},
    {"q": "She's looking forward to ___ you.", "options": ["see", "seeing", "seen"], "correct": "seeing"},
    {"q": "The more you practice, ___ you get.", "options": ["the better", "better", "the best"], "correct": "the better"},
    {"q": "I ___ been there before.", "options": ["have never", "never have", "did never"], "correct": "have never"},
    {"q": "We ___ to the party if we had known.", "options": ["would go", "would have gone", "went"], "correct": "would have gone"},
    {"q": "He's interested ___ learning Japanese.", "options": ["in", "on", "at"], "correct": "in"},
    {"q": "She accused him ___ lying.", "options": ["for", "of", "about"], "correct": "of"},
    {"q": "I'm not very good ___ math.", "options": ["in", "at", "on"], "correct": "at"},
    {"q": "They succeeded ___ finishing the project.", "options": ["to", "in", "at"], "correct": "in"},
    {"q": "He apologized ___ being late.", "options": ["about", "for", "of"], "correct": "for"},
    {"q": "The hotel ___ we stayed was excellent.", "options": ["where", "which", "that"], "correct": "where"},
    {"q": "That's the girl ___ brother is a doctor.", "options": ["who", "which", "whose"], "correct": "whose"},
    {"q": "I have three brothers, all of ___ are older.", "options": ["who", "whom", "which"], "correct": "whom"},
    {"q": "She ___ to the gym three times a week.", "options": ["go", "goes", "is going"], "correct": "goes"},
    {"q": "I'd rather you ___ quiet.", "options": ["keep", "to keep", "kept"], "correct": "kept"} 
  ],
  "B2": [  
    {"q": "The match was called ___ due to heavy rain.", "options": ["off", "out", "away"], "correct": "off"},
    {"q": "She ___ to be an expert in her field.", "options": ["is considered", "considers", "has considered"], "correct": "is considered"},
    {"q": "I wish I ___ harder for the exam.", "options": ["studied", "had studied", "would study"], "correct": "had studied"},
    {"q": "By next year, he ___ his degree.", "options": ["completes", "will have completed", "is completing"], "correct": "will have completed"},
    {"q": "The report needs ___ by Friday.", "options": ["to be submitted", "submitting", "submit"], "correct": "to be submitted"},
    {"q": "If she ___ about the meeting, she would have come.", "options": ["knew", "had known", "has known"], "correct": "had known"},
    {"q": "He's very ___ ; he always pays for dinner.", "options": ["mean", "generous", "selfish"], "correct": "generous"},
    {"q": "The company turned ___ his application.", "options": ["off", "down", "over"], "correct": "down"},
    {"q": "She ___ across an old photo while cleaning.", "options": ["came", "ran", "went"], "correct": "came"},
    {"q": "I can't put ___ with this noise anymore.", "options": ["up", "out", "off"], "correct": "up"},
    {"q": "He takes ___ his father in many ways.", "options": ["after", "over", "on"], "correct": "after"},
    {"q": "The car broke ___ on the highway.", "options": ["down", "up", "off"], "correct": "down"},
    {"q": "She looked ___ the word in the dictionary.", "options": ["up", "for", "into"], "correct": "up"},
    {"q": "We need to cut ___ on expenses.", "options": ["off", "down", "out"], "correct": "down"},
    {"q": "He gave ___ smoking last year.", "options": ["up", "away", "off"], "correct": "up"},
    {"q": "The meeting was called ___ at the last minute.", "options": ["off", "out", "in"], "correct": "off"},
    {"q": "She ran ___ an old friend at the mall.", "options": ["over", "into", "across"], "correct": "into"},
    {"q": "I'll look ___ your report tonight.", "options": ["over", "through", "into"], "correct": "over"},
    {"q": "He doesn't get ___ with his sister.", "options": ["along", "on", "over"], "correct": "along"},
    {"q": "She made ___ a story to explain her absence.", "options": ["up", "out", "off"], "correct": "up"},
    {"q": "The fire quickly got out of ___.", "options": ["control", "order", "hand"], "correct": "control"},
    {"q": "He's ___ a lot of pressure at work.", "options": ["under", "in", "on"], "correct": "under"},
    {"q": "She's ___ charge of the marketing team.", "options": ["on", "in", "at"], "correct": "in"},
    {"q": "The project is ___ schedule.", "options": ["ahead of", "in front of", "before"], "correct": "ahead of"},
    {"q": "We need to take ___ of this opportunity.", "options": ["advantage", "benefit", "profit"], "correct": "advantage"},
    {"q": "He's ___ two minds about accepting the job.", "options": ["in", "on", "at"], "correct": "in"},
    {"q": "She's ___ the verge of signing the contract.", "options": ["in", "on", "at"], "correct": "on"},
    {"q": "The company is ___ the red this year.", "options": ["in", "on", "at"], "correct": "in"},
    {"q": "He's ___ good terms with his neighbors.", "options": ["on", "in", "at"], "correct": "on"},
    {"q": "She has a ___ for languages.", "options": ["gift", "present", "skill"], "correct": "gift"},
    {"q": "The film was ___ a hit at the box office.", "options": ["so", "such", "very"], "correct": "such"},
    {"q": "He drives ___ fast that it's scary.", "options": ["so", "such", "too"], "correct": "so"},
    {"q": "I'd rather you ___ smoke in here.", "options": ["don't", "didn't", "not"], "correct": "didn't"},
    {"q": "It's high time we ___ something about it.", "options": ["do", "did", "have done"], "correct": "did"},
    {"q": "She demanded ___ speak to the manager.", "options": ["to", "that she", "for"], "correct": "to"} 
  ],
  "C1": [  
    {"q": "Had I known about the delay, I ___ left earlier.", "options": ["would have", "would", "will have"], "correct": "would have"},
    {"q": "Not until the project was finished ___ the significance of teamwork.", "options": ["did they realize", "they realized", "had they realized"], "correct": "did they realize"},
    {"q": "The company's decision to expand overseas ___ a great deal of controversy.", "options": ["gave rise to", "resulted from", "brought up"], "correct": "gave rise to"},
    {"q": "She is ___ to win the award, given her exceptional performance.", "options": ["bound", "due", "likely"], "correct": "bound"},
    {"q": "The CEO's resignation came as a ___ to everyone in the firm.", "options": ["bolt from the blue", "storm in a teacup", "flash in the pan"], "correct": "bolt from the blue"},
    {"q": "His argument was so ___ that few could find any fault with it.", "options": ["cogent", "vague", "superficial"], "correct": "cogent"},
    {"q": "The report ___ several important points that need to be addressed.", "options": ["brings to light", "takes into account", "makes for"], "correct": "brings to light"},
    {"q": "Were the government to implement the policy, it ___ significant backlash.", "options": ["would face", "will face", "faced"], "correct": "would face"},
    {"q": "She has a ___ for languages; she picked up Mandarin in six months.", "options": ["knack", "talent", "skill"], "correct": "knack"},
    {"q": "The negotiations reached a critical ___ when both sides refused to compromise.", "options": ["impasse", "stalemate", "deadlock"], "correct": "impasse"},
    {"q": "It's high time the authorities ___ action against illegal dumping.", "options": ["took", "take", "have taken"], "correct": "took"},
    {"q": "The professor's lecture ___ a wide range of topics, from philosophy to neuroscience.", "options": ["touched on", "touched off", "touched up"], "correct": "touched on"},
    {"q": "I would rather you ___ your comments until after the presentation.", "options": ["withheld", "withhold", "have withheld"], "correct": "withheld"},
    {"q": "His latest novel is ___ to be his masterpiece.", "options": ["reckoned", "considered", "thought"], "correct": "reckoned"},
    {"q": "The team's success was ___ to their innovative approach.", "options": ["attributable", "contributed", "resulted"], "correct": "attributable"},
    {"q": "She is ___ of making such a basic error; she's usually very meticulous.", "options": ["incapable", "unable", "not possible"], "correct": "incapable"},
    {"q": "The evidence ___ the defendant's alibi, casting doubt on his innocence.", "options": ["contradicts", "refutes", "opposes"], "correct": "contradicts"},
    {"q": "He has a ___ interest in ancient history, especially the Roman Empire.", "options": ["keen", "deep", "high"], "correct": "keen"},
    {"q": "The new software is ___ with most operating systems.", "options": ["compatible", "consistent", "compliant"], "correct": "compatible"},
    {"q": "Her speech was ___ and inspiring, leaving the audience moved.", "options": ["eloquent", "fluent", "articulate"], "correct": "eloquent"},
    {"q": "The company's profits have ___ over the last quarter, despite the recession.", "options": ["soared", "plummeted", "stagnated"], "correct": "soared"},
    {"q": "I can't ___ his behavior; it's completely out of character.", "options": ["account for", "allow for", "call for"], "correct": "account for"},
    {"q": "The painting was ___ to be a forgery after extensive analysis.", "options": ["revealed", "exposed", "uncovered"], "correct": "revealed"},
    {"q": "He tends to ___ on the negative aspects of any situation.", "options": ["dwell", "ponder", "contemplate"], "correct": "dwell"},
    {"q": "The treaty was signed, ___ an end to decades of conflict.", "options": ["thereby bringing", "bringing thereby", "which brought"], "correct": "thereby bringing"},
    {"q": "No sooner ___ the results than the celebrations began.", "options": ["had they announced", "they announced", "did they announce"], "correct": "had they announced"},
    {"q": "She is a very ___ person; she always sees the bright side of life.", "options": ["optimistic", "pessimistic", "realistic"], "correct": "optimistic"},
    {"q": "The project was ___ by a lack of funding and poor planning.", "options": ["hampered", "prevented", "stopped"], "correct": "hampered"},
    {"q": "His comments were ___ and irrelevant to the main discussion.", "options": ["tangential", "central", "critical"], "correct": "tangential"},
    {"q": "She ___ to be an expert in ancient manuscripts, though she had little experience.", "options": ["professed", "confessed", "admitted"], "correct": "professed"},
    {"q": "The new policy will ___ affect small businesses, particularly in rural areas.", "options": ["adversely", "favorably", "positively"], "correct": "adversely"},
    {"q": "He is ___ to making snap judgments without considering all the facts.", "options": ["prone", "liable", "subject"], "correct": "prone"},
    {"q": "The concert was called off at the eleventh ___ due to the lead singer's illness.", "options": ["hour", "minute", "moment"], "correct": "hour"},
    {"q": "I couldn't ___ what he was saying because of the noise.", "options": ["make out", "make up", "make off"], "correct": "make out"},
    {"q": "She is a woman of ___ integrity; everyone trusts her.", "options": ["unwavering", "uncompromising", "unshakeable"], "correct": "unwavering"}  
  ],
  "C2": [     
    {"q": "The chairman's resignation was ___ by a series of financial scandals.", "options": ["precipitated", "precluded", "presaged"], "correct": "precipitated"},
    {"q": "Her ___ remarks during the interview left a lasting impression on the panel.", "options": ["incisive", "invasive", "divisive"], "correct": "incisive"},
    {"q": "The artist's work defies easy ___; it blends elements of surrealism and abstract expressionism.", "options": ["categorization", "classification", "characterization"], "correct": "categorization"},
    {"q": "The treaty was seen as a ___ to lasting peace in the region.", "options": ["harbinger", "forerunner", "precursor"], "correct": "precursor"},
    {"q": "His argument was so ___ that it convinced even the most skeptical listeners.", "options": ["persuasive", "compelling", "convincing"], "correct": "compelling"},
    {"q": "The company's rapid expansion was ___ by heavy investment in technology.", "options": ["underpinned", "undermined", "underwritten"], "correct": "underpinned"},
    {"q": "She has an ___ ability to recall even the most obscure facts.", "options": ["uncanny", "eerie", "weird"], "correct": "uncanny"},
    {"q": "The professor's lecture was so ___ that many students struggled to follow it.", "options": ["abstruse", "obtuse", "abrasive"], "correct": "abstruse"},
    {"q": "The two countries have a ___ relationship, marked by both cooperation and rivalry.", "options": ["symbiotic", "sympathetic", "symptomatic"], "correct": "symbiotic"},
    {"q": "He is a man of ___ principles, never swayed by popular opinion.", "options": ["unassailable", "unapproachable", "unattainable"], "correct": "unassailable"},
    {"q": "The novel's ___ prose captivated readers from the very first page.", "options": ["lyrical", "literal", "lithic"], "correct": "lyrical"},
    {"q": "Her contribution to the field was ___; she laid the groundwork for all future research.", "options": ["seminal", "seminary", "semantic"], "correct": "seminal"},
    {"q": "The negotiations reached a(n) ___ when both sides refused to budge.", "options": ["impasse", "stalemate", "deadlock"], "correct": "impasse"},
    {"q": "He has a ___ grasp of the subject, but his presentation skills need work.", "options": ["profound", "prolific", "proactive"], "correct": "profound"},
    {"q": "The film's ending was deliberately ___, leaving the audience to interpret it themselves.", "options": ["ambiguous", "ambivalent", "ambidextrous"], "correct": "ambiguous"},
    {"q": "Her ___ memory for dates and names made her an invaluable historian.", "options": ["encyclopedic", "encyclical", "ephemeral"], "correct": "encyclopedic"},
    {"q": "The CEO's decision to step down was ___ by the board's lack of confidence.", "options": ["precipitated", "precluded", "presaged"], "correct": "precipitated"},
    {"q": "He is known for his ___ wit, which can be both charming and cutting.", "options": ["acerbic", "acidic", "acrid"], "correct": "acerbic"},
    {"q": "The theory is so ___ that only a handful of experts fully understand it.", "options": ["recondite", "reclusive", "redolent"], "correct": "recondite"},
    {"q": "Her latest work is a ___ of different genres, from mystery to romance.", "options": ["mélange", "mixture", "mangle"], "correct": "mélange"},
    {"q": "The diplomat's speech was a ___ of diplomacy and veiled threats.", "options": ["masterstroke", "masterpiece", "masterwork"], "correct": "masterstroke"},
    {"q": "He has a(n) ___ belief in the power of education to transform lives.", "options": ["unshakeable", "unreliable", "unshaken"], "correct": "unshakeable"},
    {"q": "The book provides a ___ analysis of the political landscape.", "options": ["penetrating", "penetrative", "penitent"], "correct": "penetrating"},
    {"q": "Her argument was ___ and left no room for counterargument.", "options": ["irrefutable", "irreconcilable", "irreducible"], "correct": "irrefutable"},
    {"q": "The artist's style is ___; it cannot be easily categorized.", "options": ["idiosyncratic", "idiomatic", "idiotic"], "correct": "idiosyncratic"} 
  ]
};
